
package de.uniba.dsg.soa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Fault", targetNamespace = "http://soa.dsg.uniba.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Fault {


    /**
     * 
     * @param input
     * @return
     *     returns java.lang.String
     * @throws VerificationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verify", targetNamespace = "http://soa.dsg.uniba.de/", className = "de.uniba.dsg.soa.Verify")
    @ResponseWrapper(localName = "verifyResponse", targetNamespace = "http://soa.dsg.uniba.de/", className = "de.uniba.dsg.soa.VerifyResponse")
    @Action(input = "http://soa.dsg.uniba.de/Fault/verifyRequest", output = "http://soa.dsg.uniba.de/Fault/verifyResponse", fault = {
        @FaultAction(className = VerificationException_Exception.class, value = "http://soa.dsg.uniba.de/Fault/verify/Fault/VerificationException")
    })
    public String verify(
        @WebParam(name = "input", targetNamespace = "")
        String input)
        throws VerificationException_Exception
    ;

}
