<?xml version="1.0" encoding="UTF-8"?>
<definitions name="Greetings"
             targetNamespace="http://uniba.de/dsg/soa/"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://uniba.de/dsg/soa/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <message name="GreetingsRequest">
        <part name="name" type="xsd:string"/>
    </message>
    <message name="GreetingsResponse">
        <part name="greeting" type="xsd:string"/>
    </message>

    <portType name="GreetingsPortType">
        <operation name="greet">
            <input message="tns:GreetingsRequest"/>
            <output message="tns:GreetingsResponse"/>
        </operation>
    </portType>

    <binding name="GreetingsBinding" type="tns:GreetingsPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="greet">
            <soap:operation soapAction="http://uniba.de/dsg/soa/greet"/>
            <input>
                <soap:body use="literal" namespace="http://uniba.de/ds/soa/"/>
            </input>
            <output>
                <soap:body use="literal" namespace="http://uniba.de/ds/soa/"/>
            </output>
        </operation>
    </binding>

    <service name="GreetingsService">
        <port binding="tns:GreetingsBinding" name="GreetingsPort">
            <soap:address location="http://localhost:8080/rpc-literal/GreetingsService"/>
        </port>
    </service>
</definitions>