
package de.uniba.dsg.soa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "History", targetNamespace = "http://uniba.de/dsg/soa/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface History {


    /**
     * 
     * @param parameters
     * @return
     *     returns de.uniba.dsg.soa.GetCancellorsResponse
     */
    @WebMethod
    @WebResult(name = "getCancellorsResponse", targetNamespace = "http://uniba.de/dsg/soa/", partName = "parameters")
    @Action(input = "http://uniba.de/dsg/soa/History/getCancellorsRequest", output = "http://uniba.de/dsg/soa/History/getCancellorsResponse")
    public GetCancellorsResponse getCancellors(
        @WebParam(name = "getCancellors", targetNamespace = "http://uniba.de/dsg/soa/", partName = "parameters")
        GetCancellors parameters);

}
