package de.uniba.dsg.soa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GreetingsPortType", targetNamespace = "http://uniba.de/dsg/soa/", wsdlLocation="WEB-INF/wsdl/greetings-document-literal.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GreetingsPortType {


    /**
     * 
     * @param params
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://uniba.de/dsg/soa/greet")
    @WebResult(name = "greeting", targetNamespace = "http://uniba.de/dsg/soa/", partName = "params")
    public String greet(
        @WebParam(name = "name", targetNamespace = "http://uniba.de/dsg/soa/", partName = "params")
        String params);

}
