
package de.uniba.dsg.soa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Xml2JavaService", targetNamespace = "http://uniba.de/dsg/soa/", wsdlLocation = "file:/C:/Users/Administrator/Documents/GitHub/jaxws-samples/type-mapping/xml2java%20-%20Kopie/metadata/Xml2Java.wsdl")
public class Xml2JavaService
    extends Service
{

    private final static URL XML2JAVASERVICE_WSDL_LOCATION;
    private final static WebServiceException XML2JAVASERVICE_EXCEPTION;
    private final static QName XML2JAVASERVICE_QNAME = new QName("http://uniba.de/dsg/soa/", "Xml2JavaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Administrator/Documents/GitHub/jaxws-samples/type-mapping/xml2java%20-%20Kopie/metadata/Xml2Java.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        XML2JAVASERVICE_WSDL_LOCATION = url;
        XML2JAVASERVICE_EXCEPTION = e;
    }

    public Xml2JavaService() {
        super(__getWsdlLocation(), XML2JAVASERVICE_QNAME);
    }

    public Xml2JavaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), XML2JAVASERVICE_QNAME, features);
    }

    public Xml2JavaService(URL wsdlLocation) {
        super(wsdlLocation, XML2JAVASERVICE_QNAME);
    }

    public Xml2JavaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, XML2JAVASERVICE_QNAME, features);
    }

    public Xml2JavaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Xml2JavaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Xml2Java
     */
    @WebEndpoint(name = "Xml2JavaPort")
    public Xml2Java getXml2JavaPort() {
        return super.getPort(new QName("http://uniba.de/dsg/soa/", "Xml2JavaPort"), Xml2Java.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Xml2Java
     */
    @WebEndpoint(name = "Xml2JavaPort")
    public Xml2Java getXml2JavaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://uniba.de/dsg/soa/", "Xml2JavaPort"), Xml2Java.class, features);
    }

    private static URL __getWsdlLocation() {
        if (XML2JAVASERVICE_EXCEPTION!= null) {
            throw XML2JAVASERVICE_EXCEPTION;
        }
        return XML2JAVASERVICE_WSDL_LOCATION;
    }

}
