
package de.uniba.dsg.soa;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Xml2Java", targetNamespace = "http://uniba.de/dsg/soa/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Xml2Java {


    /**
     * 
     * @param standard
     */
    @WebMethod
    @RequestWrapper(localName = "getCollection", targetNamespace = "http://uniba.de/dsg/soa/", className = "de.uniba.dsg.soa.GetCollection")
    @ResponseWrapper(localName = "getCollectionResponse", targetNamespace = "http://uniba.de/dsg/soa/", className = "de.uniba.dsg.soa.GetCollectionResponse")
    @Action(input = "http://uniba.de/dsg/soa/Java2Xml/getCollectionRequest", output = "http://uniba.de/dsg/soa/Java2Xml/getCollectionResponse")
    public void getCollection(
        @WebParam(name = "standard", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<List<String>> standard);

}
