
package de.uniba.dsg.soa;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Xml2Java", targetNamespace = "http://uniba.de/dsg/soa/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Xml2Java {


    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.datatype.Duration
     */
    @WebMethod
    @WebResult(name = "getDurationResponse", targetNamespace = "http://uniba.de/dsg/soa/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://uniba.de/dsg/soa/Java2Xml/getDurationRequest", output = "http://uniba.de/dsg/soa/Java2Xml/getDurationResponse")
    public Duration getDuration(
        @WebParam(name = "getDuration", targetNamespace = "http://uniba.de/dsg/soa/", partName = "parameters")
        Duration parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod
    @WebResult(name = "getDateTimeResponse", targetNamespace = "http://uniba.de/dsg/soa/", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://uniba.de/dsg/soa/Java2Xml/getDateTimeRequest", output = "http://uniba.de/dsg/soa/Java2Xml/getDateTimeResponse")
    public XMLGregorianCalendar getDateTime(
        @WebParam(name = "getDateTime", targetNamespace = "http://uniba.de/dsg/soa/", partName = "parameters")
        XMLGregorianCalendar parameters);

    /**
     * 
     * @param standard
     */
    @WebMethod
    @RequestWrapper(localName = "getCollection", targetNamespace = "http://uniba.de/dsg/soa/", className = "de.uniba.dsg.soa.List")
    @ResponseWrapper(localName = "getCollectionResponse", targetNamespace = "http://uniba.de/dsg/soa/", className = "de.uniba.dsg.soa.List")
    @Action(input = "http://uniba.de/dsg/soa/Java2Xml/getCollectionRequest", output = "http://uniba.de/dsg/soa/Java2Xml/getCollectionResponse")
    public void getCollection(
        @WebParam(name = "standard", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<List<Cancellor>> standard);

}
