
package de.uniba.dsg.soa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FaultService", targetNamespace = "http://soa.dsg.uniba.de/", wsdlLocation = "file:/C:/Users/Administrator/Documents/GitHub/jaxws-samples/exceptions/ex-client/wrapper-style/metadata/FaultService.wsdl")
public class FaultService
    extends Service
{

    private final static URL FAULTSERVICE_WSDL_LOCATION;
    private final static WebServiceException FAULTSERVICE_EXCEPTION;
    private final static QName FAULTSERVICE_QNAME = new QName("http://soa.dsg.uniba.de/", "FaultService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Administrator/Documents/GitHub/jaxws-samples/exceptions/ex-client/wrapper-style/metadata/FaultService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FAULTSERVICE_WSDL_LOCATION = url;
        FAULTSERVICE_EXCEPTION = e;
    }

    public FaultService() {
        super(__getWsdlLocation(), FAULTSERVICE_QNAME);
    }

    public FaultService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FAULTSERVICE_QNAME, features);
    }

    public FaultService(URL wsdlLocation) {
        super(wsdlLocation, FAULTSERVICE_QNAME);
    }

    public FaultService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FAULTSERVICE_QNAME, features);
    }

    public FaultService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FaultService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Fault
     */
    @WebEndpoint(name = "FaultPort")
    public Fault getFaultPort() {
        return super.getPort(new QName("http://soa.dsg.uniba.de/", "FaultPort"), Fault.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Fault
     */
    @WebEndpoint(name = "FaultPort")
    public Fault getFaultPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soa.dsg.uniba.de/", "FaultPort"), Fault.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FAULTSERVICE_EXCEPTION!= null) {
            throw FAULTSERVICE_EXCEPTION;
        }
        return FAULTSERVICE_WSDL_LOCATION;
    }

}
