
package de.uniba.dsg.soa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "VerificationFault", targetNamespace = "http://soa.dsg.uniba.de/")
public class VerificationFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private VerificationFaultBean faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public VerificationFault(String message, VerificationFaultBean faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public VerificationFault(String message, VerificationFaultBean faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: de.uniba.dsg.soa.VerificationFaultBean
     */
    public VerificationFaultBean getFaultInfo() {
        return faultInfo;
    }

}
