
package de.uniba.dsg.soa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GreetingsPortType", targetNamespace = "http://uniba.de/dsg/soa/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GreetingsPortType {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://uniba.de/dsg/soa/greet")
    @WebResult(name = "greeting", targetNamespace = "")
    @RequestWrapper(localName = "greet", targetNamespace = "http://uniba.de/dsg/soa/", className = "de.uniba.dsg.soa.Greet")
    @ResponseWrapper(localName = "greetResponse", targetNamespace = "http://uniba.de/dsg/soa/", className = "de.uniba.dsg.soa.GreetResponse")
    public String greet(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
